Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tercera_Entrega.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tercera_Entrega.Models;

namespace tercera_Entrega.Controllers
{
    public class MenuController : Controller
    {
        private ERFinalFinalContainer db = new ERFinalFinalContainer();

        // GET: Menus
        public ActionResult Index()
        {
            return View(db.MenuSet.ToList());
        }

        public ActionResult INICIO()
        {
            return View();
        }

        public ActionResult servicios()
        {
            return View();
        }
        public ActionResult cotizar()
        {
            return View();
        }
        public ActionResult EVENTOS()
        {
            return View();
        }


        // GET: Menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.MenuSet.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // GET: Menus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Menus/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_menu,nombre,contenido,titulo")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.MenuSet.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(menu);
        }

        // GET: Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.MenuSet.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_menu,nombre,contenido,titulo")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.MenuSet.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.MenuSet.Find(id);
            db.MenuSet.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PaginasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tercera_Entrega.Models;

namespace tercera_Entrega.Controllers
{
    public class PaginasController : Controller
    {
        private ERFinalFinalContainer db = new ERFinalFinalContainer();

        // GET: Paginas
        public ActionResult Index()
        {
            return View(db.PaginasSet.ToList());
        }

        // GET: Paginas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paginas paginas = db.PaginasSet.Find(id);
            if (paginas == null)
            {
                return HttpNotFound();
            }
            return View(paginas);
        }

        // GET: Paginas/Create
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult boton1()
        {
            return View();
        }
        public ActionResult boton2()
        {
            return View();
        }
        public ActionResult boton3()
        {
            return View();
        }
        public ActionResult como_planear()
        {
            return View();
        }
        public ActionResult por_qué()
        {
            return View();
        }
        public ActionResult sitios_interes()
        {
            return View();
        }

        // POST: Paginas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_paginas,titulo,contenido,nombre")] Paginas paginas)
        {
            if (ModelState.IsValid)
            {
                db.PaginasSet.Add(paginas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(paginas);
        }

        // GET: Paginas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paginas paginas = db.PaginasSet.Find(id);
            if (paginas == null)
            {
                return HttpNotFound();
            }
            return View(paginas);
        }

        // POST: Paginas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_paginas,titulo,contenido,nombre")] Paginas paginas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paginas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(paginas);
        }

        // GET: Paginas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paginas paginas = db.PaginasSet.Find(id);
            if (paginas == null)
            {
                return HttpNotFound();
            }
            return View(paginas);
        }

        // POST: Paginas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Paginas paginas = db.PaginasSet.Find(id);
            db.PaginasSet.Remove(paginas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>
<html lang="es">
<head>

    <title>proyecto</title>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <br />
            <div style="text-indent: 6cm;"><font color="white"><i><h2>ALQUILER ST PARA TODO TIPO DE EVENTOS  </h2></i></font></div>


            <div id="navbar" class="navbar-collapse collapse">

            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <div style="text-indent: 4cm;">
                  
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "INICIO", "Menu")</li>
                        <li>@Html.ActionLink("Servicios", "servicios", "Menu")</li>
                        <li>@Html.ActionLink("Cotizar", "cotizar", "Menu")</li>
                        <li>@Html.ActionLink("Eventos", "EVENTOS", "Menu")</li>



                    </ul>
                </div>
            </div>
        </div>

    </nav>


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img class="first-slide" src="Images/img1.jpg" alt="First slide">

                <div class="container">
                    <div class="carousel-caption">


                    </div>
                </div>
            </div>
            <div class="item">
                <img class="second-slide" src="Images/img2.jpg" alt="Second slide">
                <div class="container">
                    <div class="carousel-caption">

                    </div>
                </div>
            </div>
            <div class="item">
                <img class="third-slide" src="Images/img3.jpg" alt="Third slide">
                <div class="container">
                    <div class="carousel-caption">


                    </div>
                </div>
            </div>
            <div class="item">
                <img class="third-slide" src="Images/img4.jpg" alt="Third slide">
                <div class="container">
                    <div class="carousel-caption">

                    </div>
                </div>
            </div>
            <div class="item">
                <img class="third-slide" src="Images/img5.jpg" alt="Third slide">
                <div class="container">
                    <div class="carousel-caption">


                    </div>
                </div>
            </div>
            <div class="item">
                <img class="third-slide" src="Images/img6.jpg" alt="Third slide">
                <div class="container">
                    <div class="carousel-caption">

                    </div>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div><!-- /.carousel -->
    <br><br>
    <h2 class="text-center"><strong>SI QUIERES QUE TU EVENTO SEA EL MEJOR...</strong></h2> <h1 class="text-center"><strong>¡VISITANOS!</strong></h1>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-4">
                <br><br>
                <img class="img-circle" src="Images/6to.jpg" alt="Generic placeholder image" width="260" height="260">
                <h2>Vestidos para sillas y manteleria.</h2>
                <br>
                <p class="text-justify"><strong>Ofrecemos la mejor calidad,variedad y diseños en cuanto a el vestuario de sillas y mesas; usando la mejor manteleria que te puedan ofrecer.</strong></p>
                
                <p> @Html.ActionLink("Ver más", "boton1", "Paginas", null, new { @class = "btn btn-lg btn-primary" })</p>


            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <br><br>
                <img class="img-circle" src="Images/7mo.jpg" alt="Generic placeholder image" width="260" height="260">
                <h2>Sillas para adultos y niños. </h2>
                <br>
                <p class="text-justify"><strong>Alquieres ST te brinda gran cantidad de sillas para que no importe el numero de tus invitados, vive sin límites.</strong></p>
                <p> @Html.ActionLink("Ver más", "boton2", "Paginas", null, new { @class = "btn btn-lg btn-primary" })</p>


            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <br><br>
                <img class="img-circle" src="Images/5to.jpg" alt="Generic placeholder image" width="260" height="260">
                <h2>Mesas redondas, cuadradas y banqueteras.</h2>
                <br>
                <p class="text-justify"><strong> Observa la variedad de estilos de mesas que tenemos para tu evento. La decoración que imagines se hará realidad.  </strong></p>
                <p> @Html.ActionLink("Ver más", "boton3", "Paginas", null, new { @class = "btn btn-lg btn-primary" })</p>

            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7">
                <h2><strong> @Html.ActionLink("¿Cómo planear un evento?", "como_planear", "Paginas", null, new { @class = "featurette-heading" })</strong></h2>

               
                <p class="lead">Conózca todo lo que debe tener en cuenta a la hora de planear, organizar y llevar a cabo un evento.</p>
                <ul>

                    <h4> <li> ¿CUANDO?</li></h4>
                    <h4> <li> ¿COMO?</li></h4>
                    <h4> <li> ¿DONDE?</li></h4>
                    <h4> <li> ¿TEMÁTICA?</li></h4>
                    <h4> <li> ¿ALIMENTOS?</li></h4>
                    <h4> <li> ¿SALONES?</li></h4>
                    <h4> <li> ¿TRANSPORTE?</li></h4>


                </ul>
            </div>
            <div class="col-md-5">
                <img class="featurette-image img-responsive center-block" src="Images/w.jpg" alt="pri">
            </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7 col-md-push-5">
                <br><br><br><br><br>
                <h2><strong> @Html.ActionLink("¿Por qué un evento en alquiler ST?", "por_qué", "Paginas", null, new { @class = "featurette-heading" })</strong></h2>

                <p class="lead">Somos pioneros en el alquiler y la organización  de eventos, con 20 años de experiencia al servicio de los caqueteños; en nuestra empresa encontrarás el acompañamiento y la asesoria  necesaria para obtener con éxito lo que quieras realizar.</p>
            </div>
            <div class="col-md-5 col-md-pull-7">
                <img class="featurette-image img-responsive center-block" src="Images/4to.jpg" alt="seg">
            </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
            <h2><strong> @Html.ActionLink("Sitios de interes", "sitios_interes", "Paginas", null, new { @class = "featurette-heading" })</strong></h2>

            <br><br>
            <img src="~/Images/m.jpg" width=278 height=200 border=2 vspace=3 hspace=3 alt="Obra de K. Haring">
            <img src="~/Images/ñ.jpg" width=278 height=200 border=2 vspace=3 hspace=3 alt="Obra de K. Haring">
            <img src="~/Images/sa.jpg" width=278 height=200 border=2 vspace=3 hspace=3 alt="Obra de K. Haring">
            <img src="~/Images/4to.jpg" width=278 height=200 border=2 vspace=3 hspace=3 alt="Obra de K. Haring">


        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->
        <!-- FOOTER -->
        <footer>
            <p class="pull-right"><a href="#">Back to top</a></p>
            <font size=4><p>&copy; CONTACTANOS &middot; <a href="#">435-68-52</a> &middot; <a href="#">310-751-6619</a></p></font>
        </footer>


</body>
</html>